name: Run CURL Task 26 times every 24 hours

on:
  schedule:
    - cron: '0 0 * * *' # Runs every 24 hours at midnight UTC

jobs:
  run-curl-task:
    runs-on: ubuntu-latest

    steps:
    - name: Execute CURL Command 26 times
      run: |
        for i in {1..26}
        do
          curl -X POST 'https://api.agent301.org/completeTask' \
            -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0' \
            -H 'Accept: application/json, text/plain, */*' \
            -H 'Accept-Encoding: gzip, deflate, br, zstd' \
            -H 'Content-Type: application/json' \
            -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Microsoft Edge";v="128", "Microsoft Edge WebView2";v="128"' \
            -H 'sec-ch-ua-platform: "Windows"' \
            -H 'sec-ch-ua-mobile: ?0' \
            -H 'authorization: user=%7B%22id%22%3A1077565489%2C%22first_name%22%3A%22Mehdi%22%2C%22last_name%22%3A%22%22%2C%22username%22%3A%22ccncvv%22%2C%22language_code%22%3A%22en%22%2C%22allows_write_to_pm%22%3Atrue%7D&chat_instance=-8306884873642602183&chat_type=channel&auth_date=1726068892&hash=a2b551aff4eda86fecd61fb109be9c1f05228734bb0729e20b690d15b81b0885' \
            -H 'origin: https://telegram.agent301.org' \
            -H 'sec-fetch-site: same-site' \
            -H 'sec-fetch-mode: cors' \
            -H 'sec-fetch-dest: empty' \
            -H 'referer: https://telegram.agent301.org/' \
            -H 'accept-language: en-US,en;q=0.9' \
            -H 'priority: u=1, i' \
            -d '{"type":"video"}'
          sleep 10 # Pause 10 seconds between requests (adjust as needed)
        done
